_BASE_: ../maskformer2.yaml
MODEL:
  BACKBONE:
    NAME: "DinoV2"
  DINOV2:
    EMBED_DIM: 384
    DEPTHS: 12
    NUM_HEADS: 6
    WINDOW_SIZE: 14
    WINDOW_BLOCK_INDEXES: [0, 1, 3, 4, 6, 7, 9, 10,]
    USE_CHECKPOINT: True
    OUT_CHANNLE: 256
    SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  WEIGHTS: "" #load backbone models
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
USE_LAYER_DECAY: True
LR_DECAY_RATE: 0.65
OUTPUT_DIR: " " #outputdir