_BASE_: ../maskformer2.yaml
MODEL:
  BACKBONE:
    NAME: "VITCOMMON1"
  VITCOMMON1:
    MODEL_NAME: "vit_small_patch16_224.augreg_in1k"
    PRETRAINED: True                    # 
    PATCH_SIZE: 16                      # patch
    EMBED_DIM: 384                      
    IN_FEATURE: "last_feat"  
    OUT_CHANNELS: 256                   
    SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5] 
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]  
    SQUARE_PAD: 0                       
    NORM: "LN"                         
    USE_CHECKPOINT: True                
    
  WEIGHTS: " "
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
USE_LAYER_DECAY: True
LR_DECAY_RATE: 0.65

OUTPUT_DIR: "DINOOUTPUT_SMALLfinetune228_small"
